# Generated by Django 2.2.2 on 2019-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.IntegerField(choices=[(0, 'Medicinas'), (1, 'Alimentación'), (2, 'Vehículo'), (3, 'Articulos de Rescate'), (999, 'Otros')], default=999, verbose_name='Tipo'),
        ),
    ]
