# Generated by Django 2.2.2 on 2019-06-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190615_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voluntario',
            name='organizaciones',
        ),
    ]
