# Generated by Django 2.2.2 on 2019-06-21 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_voluntario_organizaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='es_solicitud_de_ayuda',
            field=models.BooleanField(default=False, verbose_name='¿Es una solicitud de ayuda?'),
        ),
    ]
