# Generated by Django 2.1.7 on 2019-03-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190318_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(default='', verbose_name='Descripción')),
                ('fecha_limite', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Límite')),
                ('fecha_de_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('estado', models.IntegerField(choices=[(0, 'Nueva'), (1, 'En progreso'), (2, 'Resuelta')], default=0, verbose_name='Estado')),
                ('asignada_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='api.Voluntario', verbose_name='Voluntario asignado')),
                ('asignada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_que_ha_asignado', to='api.Voluntario', verbose_name='Asignada por')),
            ],
        ),
    ]
