# Generated by Django 2.1.7 on 2019-03-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.IntegerField(choices=[(0, 'Salud'), (1, 'Alimentación'), (2, 'Transporte'), (999, 'Otros')], default=999, verbose_name='Tipo')),
            ],
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='tipo_identidad',
            field=models.IntegerField(choices=[(0, 'V'), (1, 'E')], default=0, verbose_name='Tipo de Documento de Identidad'),
        ),
        migrations.AlterUniqueTogether(
            name='voluntario',
            unique_together={('tipo_identidad', 'nro_identidad')},
        ),
    ]
