# Generated by Django 2.2.2 on 2019-06-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reporte_es_solicitud_de_ayuda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='dirigida_por',
            field=models.ManyToManyField(blank=True, related_name='dirige', to='api.Voluntario', verbose_name='Dirigida por'),
        ),
    ]
