# Generated by Django 2.2 on 2019-04-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_recursoasignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
    ]
