# Generated by Django 2.2 on 2019-04-28 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190420_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='fecha_de_reporte',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Reporte'),
            preserve_default=False,
        ),
    ]
