# Generated by Django 2.1.7 on 2019-03-18 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('radio', models.IntegerField(blank=True, null=True, verbose_name='Radio (en metros)')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Incidencia')),
                ('estado', models.IntegerField(choices=[(0, 'Nueva'), (1, 'Confirmada'), (2, 'Atendida'), (3, 'Resuelta')], default=0, verbose_name='estado')),
                ('fecha_de_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('fecha_de_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud')),
                ('radio', models.IntegerField(blank=True, null=True, verbose_name='Radio (en metros)')),
                ('contenido', models.TextField(verbose_name='Contenido del Reporte')),
                ('estado', models.IntegerField(choices=[(0, 'Sin confirmar'), (1, 'Confirmado')], default=0, verbose_name='Estado')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='api.Incidencia', verbose_name='Incidencia asociada')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
