# Generated by Django 2.2 on 2019-04-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_incidencia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripción'),
        ),
    ]
